<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chatriq - Chat & Taskmanager</title>
    <meta name="description" content="The ultimate Bootstrap based Messaging framework to help build Messaging or Chat application fast and easy. Fully responsive and crafted with modern elements and latest design">
    <meta name="keywords" content="Chatriq, chat, messaging, theme, platform" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <link rel="icon" href="chatbox/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/materialdesignicons.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/assets/vendors/material-floating-button/dist/mfb.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/app.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/theme/default-theme.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/css/util.css">
    <link rel="stylesheet" type="text/css" href="login/css/main.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="task.css" />

    <!-- AngularJS Material CSS now available via Google CDN; version 1.2.1 used here -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.2.1/angular-material.min.css">
    <link id="pagestyle" href="material-dashboard-master/assets/css/material-dashboard.min.css?v=3.0.2" rel="stylesheet" />
    <!-- Anti-flicker snippet (recommended)  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flv.js/1.3.2/flv.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/4e4a114ffc.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-messages.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-cookies.js"></script>

    <script src="js/ngStorage.js"></script>


    <!-- AngularJS Material Javascript now available via Google CDN; version 1.2.1 used here -->
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.2.1/angular-material.min.js"></script>
    <script type="text/javascript" src="js/qrcode.min.js"></script>
    <script>
        var adonis = angular.module('Admin', ['ngRoute', 'ngCookies', 'ngMaterial', 'ngCookies', 'ngMessages']);

        adonis.service('sharedData', function($http, $q, $mdToast, $cookies) {
            var self = this;
            //Toast 
            var last = {
                bottom: true,
                top: false,
                left: false,
                right: true
            };
            self.toastPosition = angular.extend({}, last);

            self.getToastPosition = function() {
                sanitizePosition();

                return Object.keys(self.toastPosition)
                    .filter(function(pos) {
                        return self.toastPosition[pos];
                    }).join(' ');
            };

            function sanitizePosition() {
                var current = self.toastPosition;

                if (current.bottom && last.top) {
                    current.top = false;
                }
                if (current.top && last.bottom) {
                    current.bottom = false;
                }
                if (current.right && last.left) {
                    current.left = false;
                }
                if (current.left && last.right) {
                    current.right = false;
                }

                last = angular.extend({}, current);
            };

            self.Toast = function(Msg, timeout) {
                console.info('Toast', Msg, timeout);
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent(Msg)
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(timeout);

                $mdToast.show(toast)
            }
            self.showActionToast = function() {
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent('Marked as read')
                    .actionKey('z')
                    .actionHint('Press the Control-"z" key combination to ')
                    .action('UNDO')
                    .dismissHint('Activate the Escape key to dismiss this toast.')
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(0);

                $mdToast.show(toast)
                    .then(function(response) {
                        if (response === 'ok') {
                            alert('You selected the \'UNDO\' action.');
                        } else {
                            $log.log('Toast dismissed.');
                        }
                    }).catch(function() {
                        $log.log('Toast failed or was forced to close early by another toast.');
                    });
            };
            self.Logout = function() {
                var Data = {}
                Data.UniqueID = $cookies.get('UniqueID');;
                var ReDirect = {
                    'Action': 'Logout',
                    'Data': JSON.stringify(Data),
                }
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>UsersApi",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    location.reload();

                }, function errorCallback(response) {

                });
            }
            self.ReDirect = function(ReDirect) {
                var ReDirect = {
                    UniqueID: "",
                    ReDirect: ReDirect
                }
                var ReDirect = {
                    'Action': 'ReDirect',
                    'Data': JSON.stringify(ReDirect),
                }
                console.info(ReDirect);
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>UsersApi",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    location.reload();
                }, function errorCallback(response) {

                });
            }
            self.UsersLoginLogs = function() {
                var postData = {
                    UniqueID: $cookies.get('UniqueID')
                };

                var data = {
                    'Action': 'UsersLoginLogs',
                    'Data': JSON.stringify(postData),
                }
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>UsersApi",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'

                    },
                }).then(function successCallback(response) {
                    var data = response.data;


                    if (data.ErrorMsg) sharedData.Toast(data.ErrorMsg, 3000);
                    if (data.ReDirect) self.ReDirect(data.ReDirect);
                    if (data.UniqueID) {
                        deferred.resolve(data);
                    }
                }, function errorCallback(response) {
                    deferred.reject(response);
                });
            };
            self.SignInSession = function() {
                var SessonInfo = {};
                SessonInfo.CreateTime = $cookies.get('CreateTime');
                var data = {
                    'Action': 'SignInSession',
                    'Data': JSON.stringify(SessonInfo),
                }
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>UsersApi",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {
                    deferred.resolve(response.data[data.Action]);
                }, function errorCallback(response) {
                    deferred.reject(response);

                });

                return deferred.promise;
            };
            //Edit
            self.Edit = function(data) {

                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>ApiEdit",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {

                    if (response.data.Data && response.data.Data.action) {
                        self.Toast('Marked as ' + response.data.Data.action, 3000);
                    } else if (response.data.ErrorMsg) {
                        self.Toast('Marked as ' + response.data.ErrorMsg.join(","), 3000);
                    } else console.info(response.data);
                }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.

                });
            };
            //List
            self.LtstData = {};
            self.List = function(data, key) {
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>UsersApi",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {
                    var data = response.data;
                    var Data = {};
                    Data.List = data[data.Action];
                    Data.Pages = data.Pages;
                    deferred.resolve(Data);
                }, function errorCallback(response) {
                    deferred.reject(response);

                });

                return deferred.promise;
            };

        });
        adonis.factory('$socketMesa', ['$http', '$q', '$cookies', 'sharedData', function($http, $q, $cookies, sharedData) {

            console.info("泡湯連線測試", $cookies.get('UniqueID'));
            var $socketMesa = this;

            var SocketList = function(UniqueID) {

                var data = {
                    'Action': 'SoakedList',
                    'Data': JSON.stringify({
                        UniqueID
                    }),
                }
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "<?PHP echo SITE_URL; ?>Swoole",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;

                    if (data.SocketList) {
                        var Socket_url = data.SocketList.pop();
                        var websocket_url = 'wss://' + Socket_url.wss + ':' + Socket_url.port + '?' + UniqueID;
                        deferred.resolve(websocket_url);
                    } else deferred.resolve('wss://adonis.tw:9501?' + UniqueID);
                }, function errorCallback(response) {
                    deferred.reject(response);
                });

                return deferred.promise;
            };



            var websocket_url = 'wss://adonis.tw:9501?' + $cookies.get('UniqueID');

            var onmessageDefer;
            var socket = {
                ws: null,
                SocketList: SocketList,
                SignInSession: null,
                connect: function(websocket_url, SignInSession) {
                    socket.SignInSession = SignInSession;
                    socket.ws = new WebSocket(websocket_url);
                    socket.ws.addEventListener('error', (event) => {
                        sharedData.Toast("訊息服務連線失敗", 3000);
                    });
                    socket.ws.addEventListener('close', (event) => {

                        sharedData.Toast("連線關閉，系統登出", 3000);
                        // sharedData.Logout();
                    })

                    socket.ws.onopen = function(event) {


                        if (onmessageDefer) {
                            socket.ws.onmessage = onmessageDefer;
                            onmessageDefer = null;
                        }

                        socket.send(socket.SignInSession);
                    };
                },
                readyState: function() {
                    if (!socket.ws || !socket.ws.readyState) return 0;
                    return socket.ws.readyState
                },
                send: function(data) {

                    data = JSON.stringify(data);
                    if (socket.ws.readyState == 1) {
                        socket.ws.send(data);
                    } else {
                        sharedData.Toast("訊息服務連線失敗", 3000);
                    }
                },
                close: function() {
                    socket.ws.close();
                },
                onmessage: function(callback) {
                    if (socket.ws && socket.ws.readyState == 1) {
                        socket.ws.onmessage = callback;
                    } else {
                        onmessageDefer = callback;
                    }

                },
            };
            // socket.ws.addEventListener('error', (event) => {
            //     socket.ws = socket.connect($cookies.get('UniqueID'));
            // });

            return socket;


        }]);
        
    </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css" rel="stylesheet">
    <style>
        .chatapp-user-list {
            flex: 0 0 25%;
        }
    </style>
</head>

<body class="default-theme" ng-app="Admin" ng-controller="AdminController as Admin"><!-- Preloader Start -->
    <div class="preloader"></div><!-- Preloader end --><!-- main wrapper start -->
    <div class="main-wrapper">
        <section>

            <div class="limiter" style="position: absolute;z-index:1;">
                <main >
                    <div class="container-login100" style="background:none;">
                        <div class="wrap-login100">

                            <span class="login100-form-title p-b-26">
                                匿名泡湯區
                            </span>
                           

                            <div class="wrap-input100 validate-input" >
                                <input class="input100" type="text" name="email" ng-model="Admin.LoginInfo.account">
                                <span class="focus-input100" data-placeholder="輸入暱稱"></span>
                            </div>


                           
                            <div class="container-login100-form-btn">
                                <div class="wrap-login100-form-btn">
                                    <div class="login100-form-bgbtn"></div>
                                    <button class="login100-form-btn" ng-click="Admin.Login()">
                                        進入泡湯區
                                    </button>
                                </div>
                            </div>
                           

                        </div>
                    </div>
                </main>
            </div>
        </section>
        <section >
        <div class="chatapp"><!-- navbar start -->
            <nav id="navbar" class="navbar navbar-expand-md navbar-light fixed-top bg-white border-bottom shadow-sm"><a class="navbar-brand" href="index.html"><img src="chatbox/assets/images/logo.svg" width="50" height="50" class="d-inline-block align-top" alt="">
                    <h1>Chatriq</h1>
                </a>
                <div class="ml-auto d-flex align-items-center">
                    <div class="iconbox iconbox-search btn-hovered-light"><i class="iconbox__icon mdi mdi-magnify"></i></div>
                    <div class="navbar-nav">
                        <div class="iconbox-group">
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-wallet-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-diamond-stone"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-bell-ring-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-dots-vertical"></i></div>
                        </div>
                        <div class="dropdown user-nav">
                            <div class="user-avatar user-avatar-sm user-avatar-rounded" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="chatriq-user chatriq-user-01"></div>
                            </div>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-outline"></i></span><span>Profile</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-multiple-plus-outline"></i></span><span>Invite
                                        People</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-settings-outline"></i></span><span>Settings</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-help-circle-outline"></i></span><span>Help</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-comment-quote-outline"></i></span><span>Feedback</span></a>
                                <div class="dropdown-divider"></div><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-logout-variant"></i></span><span>Logout</span></a>
                            </div>
                        </div>
                        <div class="iconbox-searchbar">
                            <form><input type="text" class="form-control" placeholder="Search here..." autofocus><button class="search-submit" type="submit"><i class="mdi mdi-magnify"></i></button><a href="javascript:void(0)" class="search-close"><i class="mdi mdi-arrow-left"></i></a></form>
                        </div>
                    </div>
                </div>
            </nav><!-- navbar end --><!-- sidebar start -->
            <div class="chatapp__sidebar">
                <ul class="nav" id="myTab" role="tablist">
                    <li class="nav-item"><a class="nav-link active" href="index.html"><i class="mdi mdi-message-text-outline"></i><span>Chats</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="calls.html"><i class="mdi mdi-phone-outline"></i><span>Calls</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="contacts.html"><i class="mdi mdi-account-box-outline"></i><span>Contacts</span></a></li>
                    <li class="nav-item nav-item-todo"><a class="nav-link" href="todo.html"><i class="mdi mdi-checkbox-marked-outline"></i><span>To-Do</span></a></li>
                    <li class="nav-item sidebar-bottom-nav nav-item-help"><a class="nav-link" href="help.html" title="Help"><i class="mdi mdi-help-circle-outline"></i><span>Help</span></a>
                    </li>
                </ul>
            </div><!-- sidebar end --><!-- main content start -->
            <div class="chatapp__content">
                <div class="chatapp__messagetab"><!-- user list start -->
                    <div class="chatapp-user-list">
                        <div class="chatapp-user-list-body custom-scrollbar">
                            <div class="chatapp__headingbar">
                                <h6>All Messages</h6>
                                <div class="chatapp__actions">
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-heart"></i>
                                    </div>
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-square-edit-outline"></i></div>
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-dots-horizontal-circle-outline"></i>
                                    </div>
                                </div>
                            </div>
                            <ul class="list-unstyled">
                                <li class="active">
                                    <div class="conversation ">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-11"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Jack P.
                                                    Angulo</div>
                                                <div class="conversation__time">07:15 PM</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet consectetur
                                                    adipisicing elit. Soluta consequuntur
                                                    accusantium tempora. Ad officiis voluptate
                                                    neque, deleniti porro necessitatibus aut!
                                                </div><span><i class="mdi mdi-pin"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-03"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name"><span class="conversation__name--title">Earnest
                                                    Clements</span><span class="conversation__time">07:15 PM</span>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet consectetur
                                                    adipisicing elit. Blanditiis alias placeat
                                                    repellendus voluptate quo cupiditate.
                                                </div><span><i class="mdi mdi-volume-mute"></i></span><span class="badge badge-primary badge-rounded">9</span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded offline">
                                            <div class="chatriq-user chatriq-user-04"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Willie
                                                    McLaughlin</div>
                                                <div class="conversation__time">07:15 PM</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Hi
                                                </div><span><i class="mdi mdi-volume-mute"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded recently-active">
                                            <div class="chatriq-user chatriq-user-05"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Andrew
                                                    Showalter</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded offline">
                                            <div class="chatriq-user chatriq-user-06"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Michael
                                                    L. Haley</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-07"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Irene D.
                                                    Heffner</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded recently-active">
                                            <div class="chatriq-user chatriq-user-08"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Shantelle
                                                    B. Torres</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded offline">
                                            <div class="chatriq-user chatriq-user-09"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Mary C.
                                                    Barnes</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-10"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Gerald W.
                                                    Tyson</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-02"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Willie Y.
                                                    Bollin</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded recently-active">
                                            <div class="chatriq-user chatriq-user-12"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Michael
                                                    T. Howard</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded offline">
                                            <div class="chatriq-user chatriq-user-13"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Anne T.
                                                    Jackson</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-14"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Lynne E.
                                                    Gilbreath</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="conversation">
                                        <div class="user-avatar user-avatar-rounded recently-active">
                                            <div class="chatriq-user chatriq-user-02"></div>
                                        </div>
                                        <div class="conversation__details">
                                            <div class="conversation__name">
                                                <div class="conversation__name--title">Barbara
                                                    E. Conroy</div>
                                                <div class="conversation__time">Yesterday</div>
                                            </div>
                                            <div class="conversation__message">
                                                <div class="conversation__message-preview">Lorem
                                                    ipsum dolor sit amet.</div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <ul id="mfbMenu" class="mfb-component--br mfb-slidein-spring" data-mfb-toggle="click">
                            <li class="mfb-component__wrap"><a href="#" class="mfb-component__button--main"><i class="mfb-component__main-icon--resting mdi mdi-plus ion-plus-round"></i><i class="mfb-component__main-icon--active mdi mdi-close ion-close-round"></i></a>
                                <ul class="mfb-component__list">
                                    <li><a href="javascript:;" data-mfb-label="Theme" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-palette"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="Create Group" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-account-group"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="New Call" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-phone"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="New Chat" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-android-messages"></i></a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div><!-- user list end --><!-- conversations start -->
                    <div class="chatapp__conversations"><!-- conversation wrapper start -->
                        <div class="conversation-wrapper">
                            <div class="conversation-panel">
                                <div class="conversation-panel__head">
                                    <div class="back-button-md"><i class="mdi mdi-arrow-left"></i>
                                    </div>
                                    <div class="conversation-panel__avatar info-panel-opener">
                                        <div class="user-avatar user-avatar-rounded">
                                            <div class="chatriq-user chatriq-user-11"></div>
                                        </div>
                                        <div class="conversation__name">
                                            <div class="conversation__name--title">Jack P. Angulo
                                            </div>
                                            <div class="conversation__time">last seen at 07:15 PM
                                            </div>
                                        </div>
                                    </div>
                                    <div class="conversation__actions">
                                        <div class="action-icon" data-toggle="modal" data-target="#outGoingCall" data-backdrop="static" data-keyboard="false"><i class="mdi mdi-phone"></i>
                                        </div>
                                        <div class="action-icon" data-toggle="modal" data-target="#incomingVideoStart" data-backdrop="static" data-keyboard="false"><i class="mdi mdi-video-outline"></i></div>
                                        <div class="dropdown">
                                            <div class="action-icon" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="mdi mdi-dots-vertical"></i></div>
                                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item info-panel-opener" href="javascript:;"><span><i class="mdi mdi-information-outline"></i></span><span>View
                                                        Contact</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-magnify"></i></span><span>Search</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-volume-mute"></i></span><span>Mute
                                                        notifications</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-wallpaper"></i></span><span>Wallpaper</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-trash-can-outline"></i></span><span>Delete
                                                        Chat</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-export-variant"></i></span><span>Export
                                                        Chat</span></a>
                                                <div class="dropdown-divider"></div><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-cancel"></i></span><span>Block</span></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="conversation-panel__body">
                                    <div class="custom-scrollbar2">
                                        <div class="container">
                                            <ul class="chat-style-2">
                                                <li class="message sent">
                                                    <div class="message__text">Hi<div class="metadata"><span class="time">07:14
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">How are you?
                                                        <div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Hi<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">I am fine<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">What's about
                                                        you?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">I am also fine.
                                                        <div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">Do I need a
                                                        jacket?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Yup. It's
                                                        chilly.<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">Sunglasses?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Sorry, I was
                                                        trying to charge my phone. What are
                                                        you trying to say?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">Do I need
                                                        sunglasses?<div class="metadata">
                                                            <span class="time">07:15
                                                                AM</span>
                                                        </div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Your future's
                                                        so bright. Gotta wear shades!<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">What about an
                                                        umbrella?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Excuse me?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">What's the
                                                        weather like this weekend?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Are you on a
                                                        boat? Because I was not able to find
                                                        any results for that location.<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">What's the
                                                        weather like in Brooklyn this
                                                        weekend?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">The weather in
                                                        Brooklyn, NY is 0 46°F and clear.
                                                        <div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">This weekend?
                                                        <div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Excusez-moi?
                                                        <div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message received">
                                                    <div class="message__text">Sorry, dozed
                                                        off for a second. What were you
                                                        saying?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">Whats about
                                                        weather in this weekend?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                                <li class="message sent">
                                                    <div class="message__text">hello, are you
                                                        there ?<div class="metadata"><span class="time">07:15
                                                                AM</span></div>
                                                    </div>
                                                    <div class="message__options"><i class=" mdi mdi-dots-horizontal"></i>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="conversation-panel__footer">
                                    <div class="composer">
                                        <div class="composer__left">
                                            <div class="composer__left--sticker"><i class="mdi mdi-sticker-emoji"></i></div>
                                            <div class="composer__left--emoticon"><i class="mdi mdi-emoticon-outline"></i>
                                            </div>
                                        </div>
                                        <div class="composer__middle"><textarea class="form-control" rows="1" placeholder="Type a message..."></textarea>
                                            <div class="composer__middle--microphone"><i class="mdi mdi-microphone"></i></div>
                                            <div class="composer__middle--photo"><i class="mdi mdi-camera"></i></div>
                                            <div class="composer__middle--attachment"><i class="mdi mdi-attachment"></i></div>
                                        </div>
                                        <div class="composer__right">
                                            <div class="composer__right--send"><i class="mdi mdi-send"></i></div>
                                            <div class="composer__right--microphone"><i class="mdi mdi-microphone"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- conversation panel end --><!-- information panel start -->
                        <div class="information-panel">
                            <div class="information-panel__head">
                                <h5>Contact info</h5>
                                <div class="information-panel__closer"><i class="mdi mdi-close"></i>
                                </div>
                            </div>
                            <div class="information-panel__body custom-scrollbar">
                                <div class="userprofile-avatar"><img src="chatbox/assets/images/user/150/01.jpg" alt=""></div>
                                <div class="userprofile-name">
                                    <h4>Jack P. Angulo</h4><span>Product Manager</span>
                                    <div class="social-icon-box">
                                        <div class="social-icon"><i class="mdi mdi-facebook"></i>
                                        </div>
                                        <div class="social-icon"><i class="mdi mdi-linkedin"></i>
                                        </div>
                                        <div class="social-icon"><i class="mdi mdi-twitter"></i>
                                        </div>
                                        <div class="social-icon"><i class="mdi mdi-youtube"></i>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <table class="table table-sm table-borderless user-table-info">
                                    <tr>
                                        <td><i class="mdi mdi-cellphone-android"></i></td>
                                        <td>+91 99041-99041</td>
                                    </tr>
                                    <tr>
                                        <td><i class="mdi mdi-web"></i></td>
                                        <td>www.jackangulo.com</td>
                                    </tr>
                                    <tr>
                                        <td><i class="mdi mdi-map-marker"></i></td>
                                        <td>2519 Burnside Court, HORICON, WI, 53032</td>
                                    </tr>
                                </table>
                                <hr>
                                <div class="accordion accordion-ungrouped mb-3" id="accordionExample">
                                    <div class="card">
                                        <div class="card-header" id="headingOne">
                                            <div class="card-title" data-toggle="collapse" role="button" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                <div class="acpanel__heading">
                                                    <div class="acpanel__left"><span><i class="mdi mdi-camera-outline"></i></span><span>Photos
                                                            & Media</span></div>
                                                    <div class="acpanel__right"><span class="badge badge-info">26</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <div class="slick-slider">
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/01.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/02.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/03.png" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/04.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/05.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/06.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/07.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/04.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/02.jpg" alt=""></div>
                                                    <div><img class="img-fluid" src="chatbox/assets/images/media/04.jpg" alt=""></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-header" id="headingTwo">
                                            <div class="card-title collapsed d-flex justify-content-between align-items-center" role="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                <div class="acpanel__heading">
                                                    <div class="acpanel__left"><span><i class="mdi mdi-file-document-outline"></i></span><span>Documents</span>
                                                    </div>
                                                    <div class="acpanel__right"><span class="badge badge-info">16</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <ul class="list-unstyled documentlist-wrapper">
                                                    <li>
                                                        <div class="doclist">
                                                            <div class="docicon iconbox btn-solid-danger">
                                                                <i class="iconbox__icon mdi mdi-file-pdf-box"></i>
                                                            </div>
                                                            <div class="doctitle">
                                                                <div class="docname">
                                                                    example-file.pdf
                                                                </div>
                                                                <div class="docsize">
                                                                    217kb</div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="doclist">
                                                            <div class="docicon iconbox btn-solid-info">
                                                                <i class="iconbox__icon mdi mdi-file-word-box"></i>
                                                            </div>
                                                            <div class="doctitle">
                                                                <div class="docname">
                                                                    example-file.docs
                                                                </div>
                                                                <div class="docsize">
                                                                    217kb</div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="doclist">
                                                            <div class="docicon iconbox btn-solid-success">
                                                                <i class="iconbox__icon mdi mdi-file-excel-box"></i>
                                                            </div>
                                                            <div class="doctitle">
                                                                <div class="docname">
                                                                    example-file.xlxs
                                                                </div>
                                                                <div class="docsize">
                                                                    217kb</div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="doclist">
                                                            <div class="docicon iconbox btn-solid-warning">
                                                                <i class="iconbox__icon mdi mdi-file-powerpoint-box"></i>
                                                            </div>
                                                            <div class="doctitle">
                                                                <div class="docname">
                                                                    example-file.pptx
                                                                </div>
                                                                <div class="docsize">
                                                                    217kb</div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="doclistall">View All
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-header" id="headingFour">
                                            <div class="card-title collapsed  d-flex justify-content-between align-items-center" role="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                                <div class="acpanel__heading">
                                                    <div class="acpanel__left"><span><i class="mdi mdi-settings-outline"></i></span><span>Settings</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <ul class="list-unstyled">
                                                    <li>
                                                        <div class="setting-list">
                                                            <div class="setting-list-name">
                                                                Media Auto Download
                                                            </div>
                                                            <div class="setting-list-switch">
                                                                <div class="custom-control custom-switch">
                                                                    <input type="checkbox" class="custom-control-input" id="customSwitch1"><label class="custom-control-label" for="customSwitch1"></label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="setting-list">
                                                            <div class="setting-list-name">
                                                                Mute Conversation</div>
                                                            <div class="setting-list-switch">
                                                                <div class="custom-control custom-switch">
                                                                    <input type="checkbox" class="custom-control-input" id="customSwitch2"><label class="custom-control-label" for="customSwitch2"></label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="setting-list">
                                                            <div class="setting-list-name">
                                                                Notifications</div>
                                                            <div class="setting-list-switch">
                                                                <div class="custom-control custom-switch">
                                                                    <input type="checkbox" class="custom-control-input" id="customSwitch3"><label class="custom-control-label" for="customSwitch3"></label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="setting-list">
                                                            <div class="setting-list-name">
                                                                Block</div>
                                                            <div class="setting-list-switch">
                                                                <div class="custom-control custom-switch">
                                                                    <input type="checkbox" class="custom-control-input" id="customSwitch4"><label class="custom-control-label" for="customSwitch4"></label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- information panel end -->
                    </div><!-- conversations end -->
                </div>
            </div><!-- main content end -->
        </div><!-- VIDEO CALL START-->
        <div class="modal fade videocall-modal CallDialogFullscreen-sm" id="incomingVideoStart" tabindex="-1" role="dialog" aria-labelledby="incomingVideoStart" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="icvideocallwrapper">
                            <div class="icvideo-contact"><img class="img-fluid icvideo-contact__inner" src="chatbox/assets/images/media/call-01.jpg" alt=""></div>
                            <div class="icvideo-user"><img src="chatbox/assets/images/user/150/01.jpg" alt="">
                            </div>
                            <div class="icvideo-actions">
                                <div class="icvideo-actions__left">
                                    <div class="icvideo-actions__left--duration">00:36</div>
                                </div>
                                <div class="icvideo-actions__middle">
                                    <div class="">
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Speaker"><i class="iconbox__icon mdi mdi-volume-high"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Hold"><i class="iconbox__icon mdi mdi-pause"></i></div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Add Call"><i class="iconbox__icon mdi mdi-phone-plus"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Disbale Video"><i class="iconbox__icon mdi mdi-video-off-outline"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Mute"><i class="iconbox__icon mdi mdi-microphone-off"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="icvideo-actions__right">
                                    <div class="iconbox btn-hovered-light bg-danger" data-dismiss="modal" data-toggle="tooltip" data-placement="top" title="Hangup"><i class="iconbox__icon text-white mdi mdi-phone-hangup"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- OUTGOING VOICE CALL -->
        <div class="modal CallDialogFullscreen-sm" id="outGoingCall" tabindex="-1" role="dialog" aria-labelledby="outGoingCall" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="text-center">
                            <div class="user-avatar user-avatar-rounded user-avatar-xl"><img src="chatbox/assets/images/user/80/01.jpg" alt=""></div>
                            <div class="userprofile-name"><span>Calling...</span>
                                <h4>Jack P. Angulo</h4><span>Product Manager</span>
                                <div class="call-duration">00:36</div>
                            </div>
                            <div class="call-options">
                                <div class="row">
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-microphone-off"></i></div>
                                        <h6>Mute</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-volume-high"></i></div>
                                        <h6>Speaker</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-pause"></i></div>
                                        <h6>Hold</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="call-actions">
                                <div class="call-hangup" data-dismiss="modal"><i class="mdi mdi-phone-hangup"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>
    </div><!-- main wrapper end --><!-- Javascripts Files -->
    <script>
        adonis.controller('AdminController', ['sharedData', '$scope', '$http', '$cookies','$socketMesa', function(sharedData, $scope, $http, $cookies, $socketMesa) {

            var Admin = this;
            Admin.LoginInfo = {};
        }]);
    </script>
    <script src="chatbox/dist/js/jquery-3.3.1.slim.min.js"></script>
    <script src="chatbox/assets/vendors/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="chatbox/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="chatbox/assets/vendors/shortable/sortable.min.js"></script>
    <script src="chatbox/dist/js/main.js"></script>
    
</body>

</html>