<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chatriq - Chat & Taskmanager</title>
    <meta name="description" content="The ultimate Bootstrap based Messaging framework to help build Messaging or Chat application fast and easy. Fully responsive and crafted with modern elements and latest design">
    <meta name="keywords" content="Chatriq, chat, messaging, theme, platform" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <link rel="icon" href="chatbox/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/materialdesignicons.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/app.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/theme/default-theme.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/css/util.css">
    <link rel="stylesheet" type="text/css" href="login/css/main.css">
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css" href="chatbox.css" />

    <!-- Anti-flicker snippet (recommended)  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flv.js/1.3.2/flv.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/4e4a114ffc.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-messages.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/21.2.6/js/dx.all.js"></script>

    <!-- AngularJS Material Javascript now available via Google CDN; version 1.2.1 used here -->
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.2.1/angular-material.min.js"></script>
    <script>
        var adonis = angular.module('Admin', ['ngRoute', 'ngMaterial', 'ngMessages', 'dx']);
        adonis.directive("imgUpload", function($http, $compile, $parse) {
            return {
                restrict: 'AE',
                require: '?ngModel',
                scope: {
                    url: "@",
                    method: "@"
                },
                template: '<input class="fileUpload" type="file" multiple />' +
                    '<div class="dropzone">' +
                    '<p class="msg">Click or Drag and Drop files to upload</p>' +
                    '</div>' +
                    '<div class="preview clearfix">' +
                    '<div class="previewData clearfix" ng-repeat="data in previewData track by $index">' +
                    '<div class="previewDetails">' +
                    '<div class="card" ><div class="card_image"> <img src="" ng-src="{{data.src}}" /></div></div>'+
                    '<div class="detail"><b>Name : </b>{{data.name}}</div>' +
                    '<div class="detail"><b>Type : </b>{{data.type}}</div>' +
                    '<div class="detail"><b>Size : </b> {{data.size}}</div>' +
                    '</div>' +
                    '<div class="previewControls">' +
                    '<span ng-click="upload(data)" class="circle upload">' +
                    '<i class="fa fa-check"></i>' +
                    '</span>' +
                    '<span ng-click="remove(data)" class="circle remove">' +
                    '<i class="fa fa-close"></i>' +
                    '</span>' +
                    '</div>' +
                    '</div>' +
                    '</div>',
                link: function(scope, elem, attrs, ngModelCtrl) {
                    var formData = new FormData();
                    var model = $parse(attrs.ngModel);

                    scope.previewData = [];

                    function previewFile(file) {
                        var reader = new FileReader();
                        var obj = new FormData().append('file', file);
                        reader.onload = function(data) {
                            var src = data.target.result;
                            var size = ((file.size / (1024 * 1024)) > 1) ? (file.size / (1024 * 1024)) + ' mB' : (file.size / 1024) + ' kB';
                            scope.$apply(function() {
                                scope.previewData.push({
                                    'name': file.name,
                                    'size': size,
                                    'type': file.type,
                                    'src': src,
                                    'data': obj
                                });
                            });
                            console.log(scope.previewData);
                        }
                        reader.readAsDataURL(file);
                    }

                    function uploadFile(e, type) {
                        e.preventDefault();
                        var files = "";
                        if (type == "formControl") {
                            files = e.target.files;
                        } else if (type === "drop") {
                            files = e.originalEvent.dataTransfer.files;
                        }
                        for (var i = 0; i < files.length; i++) {
                            var file = files[i];
                            if (file.type.indexOf("image") !== -1) {
                                previewFile(file);
                            } else {
                                alert(file.name + " is not supported");
                            }
                        }
                    }
                    elem.find('.fileUpload').bind('change', function(e) {
                        uploadFile(e, 'formControl');
                    });

                    elem.find('.dropzone').bind("click", function(e) {
                        $compile(elem.find('.fileUpload'))(scope).trigger('click');
                    });

                    elem.find('.dropzone').bind("dragover", function(e) {
                        e.preventDefault();
                    });

                    elem.find('.dropzone').bind("drop", function(e) {
                        uploadFile(e, 'drop');
                    });
                    scope.upload = function(obj) {
                        obj.Seller = ngModelCtrl.$modelValue;
                        $http({
                            method: scope.method,
                            url: scope.url,
                            data: obj,
                            headers: {
                                'Content-Type': undefined
                            },
                            // transformRequest: angular.identity
                        }).then(function successCallback(response) {
                            var data = response.data;
                            console.info(data);
                            if (data.src) ngModelCtrl.$modelValue.push(data.src)

                        }, function errorCallback(response) {
                            console.info(response);

                        });
                    }

                    scope.remove = function(data) {
                        var index = scope.previewData.indexOf(data);
                        scope.previewData.splice(index, 1);
                    }
                }
            }
        });
        adonis.factory('socket', [function() {
            var stack = [];
            var onmessageDefer;
            var websocket_url = 'wss://swoole.bestaup.com:9509';
            var socket = {
                ws: new WebSocket(websocket_url),
                send: function(data) {
                    data = JSON.stringify(data);
                    if (socket.ws.readyState == 1) {
                        socket.ws.send(data);
                    } else {
                        stack.push(data);
                    }
                },
                onmessage: function(callback) {
                    if (socket.ws.readyState == 1) {
                        socket.ws.onmessage = callback;
                    } else {
                        onmessageDefer = callback;
                    }
                }
            };
            socket.ws.onopen = function(event) {
                for (i in stack) {
                    socket.ws.send(stack[i]);
                }
                stack = [];
                if (onmessageDefer) {
                    socket.ws.onmessage = onmessageDefer;
                    onmessageDefer = null;
                }
            };
            return socket;
        }]);
        adonis.service('sharedData', function($http, $q, $mdToast) {
            var self = this;
            //Toast 
            var last = {
                bottom: true,
                top: false,
                left: false,
                right: true
            };
            self.toastPosition = angular.extend({}, last);

            self.getToastPosition = function() {
                sanitizePosition();

                return Object.keys(self.toastPosition)
                    .filter(function(pos) {
                        return self.toastPosition[pos];
                    }).join(' ');
            };

            function sanitizePosition() {
                var current = self.toastPosition;

                if (current.bottom && last.top) {
                    current.top = false;
                }
                if (current.top && last.bottom) {
                    current.bottom = false;
                }
                if (current.right && last.left) {
                    current.left = false;
                }
                if (current.left && last.right) {
                    current.right = false;
                }

                last = angular.extend({}, current);
            };

            self.Toast = function(Msg, timeout) {
                console.info('Toast', Msg, timeout);
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent(Msg)
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(timeout);

                $mdToast.show(toast)
            }
            self.showActionToast = function() {
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent('Marked as read')
                    .actionKey('z')
                    .actionHint('Press the Control-"z" key combination to ')
                    .action('UNDO')
                    .dismissHint('Activate the Escape key to dismiss this toast.')
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(0);

                $mdToast.show(toast)
                    .then(function(response) {
                        if (response === 'ok') {
                            alert('You selected the \'UNDO\' action.');
                        } else {
                            $log.log('Toast dismissed.');
                        }
                    }).catch(function() {
                        $log.log('Toast failed or was forced to close early by another toast.');
                    });
            };
            self.Logout = function() {
                var Data = {}
                Data.UniqueID = "";
                var ReDirect = {
                    'Action': 'Logout',
                    'Data': JSON.stringify(Data),
                }
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/api",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    location.reload();

                }, function errorCallback(response) {

                });
            }
            self.ReDirect = function(ReDirect) {
                var ReDirect = {
                    UniqueID: "",
                    ReDirect: ReDirect
                }
                var ReDirect = {
                    'Action': 'ReDirect',
                    'Data': JSON.stringify(ReDirect),
                }
                console.info(ReDirect);
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/api",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    if (data.ReDirect == "reload") location.reload();
                    else console.info(data);
                }, function errorCallback(response) {

                });
            }
            //Edit
            self.Edit = function(data) {

                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/ApiEdit",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {

                    if (response.data.Data && response.data.Data.action) {
                        self.Toast('Marked as ' + response.data.Data.action, 3000);
                    } else if (response.data.ErrorMsg) {
                        self.Toast('Marked as ' + response.data.ErrorMsg.join(","), 3000);
                    } else console.info(response.data);
                }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.

                });
            };
            //List
            self.LtstData = {};
            self.List = function(data, key) {
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/UsersApi",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {
                    var data = response.data;
                    var Data = {};
                    Data.List = data[data.Action];
                    Data.Pages = data.Pages;
                    deferred.resolve(Data);
                }, function errorCallback(response) {
                    deferred.reject(response);

                });

                return deferred.promise;
            };

        });
    </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css" rel="stylesheet">
    <style>
        .chatapp-user-list {
            flex: 0 0 25%;
        }

        .ca-profile-pic img {
            width: 100%;
            height: 100%;
        }
    </style>
    <style>
        .bg-gradient-primary {
            background-image: linear-gradient(195deg, #0b1048 0%, #4e5bb9 100%);
        }

        .shadow-primary {
            box-shadow: 0 4px 20px 0 rgb(0 0 0 / 14%), 0 7px 10px -5px rgb(34 10 143 / 37%) !important;
        }

        .btn-primary,
        .btn.bg-gradient-primary {
            box-shadow: 0 3px 3px 0 rgb(51 30 233 / 15%), 0 3px 1px -2px rgb(30 42 233 / 20%), 0 1px 5px 0 rgb(30 39 233 / 15%);
        }

        #pie {
            height: 440px;
        }

        .clearfix {
            overflow: auto;
        }

        .dropzone {
            position: relative;
            height: 200px;
            border: 2px dashed #b3b3b3;
            border-radius: 4px;
            background-color: #f3f3f3;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        .dropzone .msg {
            font-size: 20px;
            font-weight: bold;
            color: #c3c3c3;
            padding: 0 10px;
        }

        input.fileUpload {
            display: none;
        }

        .preview {
            margin: 10px 0;
            padding: 5px;
        }

        .previewData img {
            width: 100px;
            height: 100px;
            float: left;
            margin: 5px;
        }

        .previewDetails {
            display: inline-block;
            float: left;
            margin: 5px;
            padding: 8px;
        }

        .detail {
            font-family: arial;
            padding: 5px;
            overflow: hidden;
            max-width: 200px;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .previewControls {
            display: inline-block;
            float: left;
            margin: 40px 30px;
        }

        .circle {
            border: 2px solid #5B93F5;
            border-radius: 20px;
            display: inline-block;
            height: 25px;
            width: 25px;
            margin: 5px;
            cursor: pointer;
            color: #5B93F5;
            line-height: initial;
        }

        .circle.upload:hover {
            border: 2px solid green;
        }

        .circle.upload:hover i.fa-check {
            color: green;
        }

        .circle.remove:hover {
            border: 2px solid red;
        }

        .circle.remove:hover i.fa-close {
            color: red;
        }

        .circle i {
            position: relative;
            font-size: 14px;
        }

        .circle i.fa-check {
            top: 3px;
            left: 5px;
        }

        .circle i.fa-close {
            top: 2px;
            left: 7px;
        }
    </style>
</head>

<body class="default-theme" ng-app="Admin">
    <!-- Preloader Start -->
    <div class="preloader"></div><!-- Preloader end -->
    <!-- main wrapper start -->
    <div class="main-wrapper" ng-controller="AdminController as Admin">
        <div class="chatapp">
            <!-- navbar start -->
            <nav id="navbar" class="navbar navbar-expand-md navbar-light fixed-top bg-white border-bottom shadow-sm"><a class="navbar-brand" href="index.html"><img src="chatbox/assets/images/logo.svg" width="50" height="50" class="d-inline-block align-top" alt="">
                    <h1>Chatriq</h1>
                </a>
                <div class="ml-auto d-flex align-items-center">
                    <div class="iconbox iconbox-search btn-hovered-light"><i class="iconbox__icon mdi mdi-magnify"></i></div>
                    <div class="navbar-nav">
                        <div class="iconbox-group">
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-wallet-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-diamond-stone"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-bell-ring-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-dots-vertical"></i></div>
                        </div>
                        <div class="dropdown user-nav">
                            <div class="user-avatar user-avatar-sm user-avatar-rounded" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="chatriq-user chatriq-user-01"></div>
                            </div>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-outline"></i></span><span>Profile</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-multiple-plus-outline"></i></span><span>Invite
                                        People</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-settings-outline"></i></span><span>Settings</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-help-circle-outline"></i></span><span>Help</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-comment-quote-outline"></i></span><span>Feedback</span></a>
                                <div class="dropdown-divider"></div><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-logout-variant"></i></span><span>Logout</span></a>
                            </div>
                        </div>
                        <div class="iconbox-searchbar">
                            <form><input type="text" class="form-control" placeholder="Search here..." autofocus><button class="search-submit" type="submit"><i class="mdi mdi-magnify"></i></button><a href="javascript:void(0)" class="search-close"><i class="mdi mdi-arrow-left"></i></a></form>
                        </div>
                    </div>
                </div>
            </nav><!-- navbar end -->
            <!-- sidebar start -->
            <div class="chatapp__sidebar">
                <ul class="nav" id="myTab" role="tablist">
                    <li class="nav-item"><a class="nav-link active" href="index.html"><i class="mdi mdi-message-text-outline"></i><span>Chats</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="calls.html"><i class="mdi mdi-phone-outline"></i><span>Calls</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="contacts.html"><i class="mdi mdi-account-box-outline"></i><span>Contacts</span></a></li>
                    <li class="nav-item nav-item-todo"><a class="nav-link" href="todo.html"><i class="mdi mdi-checkbox-marked-outline"></i><span>To-Do</span></a></li>
                    <li class="nav-item sidebar-bottom-nav nav-item-help"><a class="nav-link" href="help.html" title="Help"><i class="mdi mdi-help-circle-outline"></i><span>Help</span></a>
                    </li>
                </ul>
            </div><!-- sidebar end -->
            <!-- main content start -->
            <div class="chatapp__content">
            <div class="chatapp__contactstab">
                    <!-- user list start -->
                    <div class="chatapp-user-list">
                        <div class="chatapp-user-list-body custom-scrollbar">
                            <ul class="list-unstyled">
                                <li class="border-bottom-0">
                                    <div class="contactlist-heading"><span>Favourite</span></div>
                                </li>
                                <li>
                                    <div class="contactlist">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-02"></div>
                                        </div>
                                        <div class="contactlist__details">
                                            <div class="contactlist__details--name">Jack P. Angulo</div>
                                            <div class="contactlist__details--info">Brother</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="active">
                                    <div class="contactlist">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-03"></div>
                                        </div>
                                        <div class="contactlist__details">
                                            <div class="contactlist__details--name">Willie McLaughlin</div>
                                            <div class="contactlist__details--info">Sister</div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="contactlist">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-04"></div>
                                        </div>
                                        <div class="contactlist__details">
                                            <div class="contactlist__details--name">Andrew Showalter</div>
                                            <div class="contactlist__details--info">Father</div>
                                        </div>
                                    </div>
                                </li>
                                <li class="border-bottom-0">
                                    <div class="contactlist-heading"><span>A</span></div>
                                </li>
                                <li ng-repeat=" item in Admin.Users_List " ng-click=" Admin.UserInfo = item ">
                                    <div class="contactlist">
                                        <div class="user-avatar user-avatar-rounded online">
                                            <div class="chatriq-user chatriq-user-05"></div>
                                        </div>
                                        <div class="contactlist__details">
                                            <div class="contactlist__details--name">{{item.email}}
                                            </div>
                                            <div class="contactlist__details--info">{{item.mobile}}</div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div><!-- user list end -->
                    <!-- conversations start -->
                    <div class="chatapp__conversations">
                        <!-- contact profile wrapper start -->
                        <div class="contactist-profile-wrapper custom-scrollbar">
                            <div class="container">
                                <div class="back-button-md back2contacts"><i class="mdi mdi-arrow-left"></i><span>Back</span></div>
                                <div class="ca-profile-thumb" style="{{Admin.UserCoverItem}}">
                                    <div class="ca-profile-info">
                                        <div class="ca-profile-pic"><img ng-src="{{Admin.profile}}" alt=""></div>
                                    </div>
                                    <div class="ca-profile-actions">
                                        <div class="iconbox-group">
                                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-star-outline"></i></div>
                                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-pencil-outline"></i></div>
                                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-dots-horizontal"></i></div>
                                        </div>
                                    </div>
                                    <div class="ca-overlay"></div>
                                </div>
                                <div class="profile-settings-list border mb-5">
                                    <div class="ca-profile-title">
                                        <h2 class="ca-profile-name">Pearl Villarreal</h2>
                                        <div class="ca-profile-tag"><span>Co-Workers</span></div>
                                        <div class="ca-contcat-profile__calling-buttons pt-2">
                                            <div class="iconbox iconbox-pill btn-outline-light"><i class="iconbox__icon mdi mdi-message-text-outline"></i><span>Message</span>
                                            </div>
                                            <div class="iconbox iconbox-pill btn-outline-light"><i class="iconbox__icon mdi mdi-phone"></i><span>Voice Call</span></div>
                                            <div class="iconbox iconbox-pill btn-outline-light"><i class="iconbox__icon mdi mdi-video-outline"></i><span>Video Call</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="setting-sunheading  setting-sunheading-style01  my-3">Personal & Contact
                                        Information</div>
                                    <ul class="list-unstyled">
                                        <li>


                                            <div class="ps-list__left--icon"><i class="mdi mdi-account-heart-outline"></i></div>

                                            <div class="wrap-input100 validate-input" data-validate="Valid Nick is min lenght > 6">
                                                <input class="input100" type="text" name="Nick name" minlength="6">
                                                <span class="focus-input100" data-placeholder="Nick name"></span>
                                            </div>


                                        </li>
                                        <li>
                                            <div class="ps-list__left--icon"><i class="mdi mdi-cellphone-android"></i></div>
                                            <div class="wrap-input100 validate-input" data-validate="Valid Mobile is: 0912345678">
                                                <input class="input100" type="phome" name="Mobile number">
                                                <span class="focus-input100" data-placeholder="Mobile number"></span>
                                            </div>

                                        </li>
                                        <li>
                                            <div class="ps-list__left--icon"><i class="mdi mdi-email-outline"></i>
                                            </div>
                                            <div class="wrap-input100 validate-input" data-validate="Valid email is: a@b.c">
                                                <input class="input100" type="email" name="Email">
                                                <span class="focus-input100" data-placeholder="Email"></span>
                                            </div>

                                        </li>

                                    </ul>
                                    {{Admin.UserInfo}}
                                    <div class="setting-sunheading setting-sunheading-style01 my-4">圖片</div>
                                    <div class="cards-list">
                                        <div class="card" ng-repeat=" item in Admin.UserInfo.Images " ng-click="Admin.UserCover(item)">
                                            <div class="card_image"> <img src="" ng-src="{{item}}" />
                                            </div>
                                            <div class="card_title title-white">
                                                <p>Card Title</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="setting-sunheading setting-sunheading-style01 my-4">影片</div>
                                    <div class="cards-list">
                                        <div class="card" ng-repeat=" item in Admin.UserInfo.Videos " ng-click="Admin.UserCover(item)">
                                            <div class="card_image"> <img src="" ng-src="{{item}}" />
                                            </div>
                                            <div class="card_title title-white">
                                                <p>Card Title</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="setting-sunheading setting-sunheading-style01 my-4">上傳圖片</div>
                                    <div class="cards-list">
                                        <div class="card" ng-repeat=" item in Admin.UserImages " ng-click="Admin.UserCover(item)">
                                            <div class="card_image"> <img src="" ng-src="{{item}}" />
                                            </div>
                                            <div class="card_title title-white">
                                                <p>Card Title</p>
                                            </div>
                                        </div>
                                    </div>

                                    <div img-upload method="PUT" url="Uploads/images" ng-model="Admin.UserImages"></div>
                                </div>
                            </div>
                        </div><!-- contact profile wrapper end -->
                    </div>


                    <!-- conversation wrapper start -->

                </div>
            </div><!-- main content end -->
        </div><!-- VIDEO CALL START-->
        <div class="modal fade videocall-modal CallDialogFullscreen-sm" id="incomingVideoStart" tabindex="-1" role="dialog" aria-labelledby="incomingVideoStart" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="icvideocallwrapper">

                            <div class="icvideo-contact"><video id="video" playsinline style="width:100%"></video>
                                <img id="img" style="width:100%">
                                <canvas id="canvas" style="display: none;width:100%"></canvas>
                            </div>
                            <div class="icvideo-user"><img src="chatbox/assets/images/user/150/01.jpg" alt="">
                            </div>
                            <div class="icvideo-actions">
                                <div class="icvideo-actions__left">
                                    <div class="icvideo-actions__left--duration">00:36</div>
                                </div>
                                <div class="icvideo-actions__middle">
                                    <div class="">
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Speaker"><i class="iconbox__icon mdi mdi-volume-high"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Hold"><i class="iconbox__icon mdi mdi-pause"></i></div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Add Call"><i class="iconbox__icon mdi mdi-phone-plus"></i>
                                        </div>

                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" ng-click="Admin.CameraStop()" data-placement="top" title="Disbale Video">
                                            <i class="iconbox__icon mdi mdi-video-off-outline"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Mute"><i class="iconbox__icon mdi mdi-microphone-off"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="icvideo-actions__right">
                                    <div class="iconbox btn-hovered-light bg-danger" ng-click="Admin.CameraStop();" data-dismiss="modal" data-toggle="tooltip" data-placement="top" title="Hangup"><i class="iconbox__icon text-white mdi mdi-phone-hangup"></i>
                                    </div>
                                </div>
                                <button id="RecordBlob" ng-click="Admin.RecordBlob()">RecordBlob</button>
                                <button id="RecordStopBlob" ng-click="Admin.RecordStopBlob()">RecordStopBlob</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- OUTGOING VOICE CALL -->
        <div class="modal CallDialogFullscreen-sm" id="outGoingCall" tabindex="-1" role="dialog" aria-labelledby="outGoingCall" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="text-center">
                            <div class="user-avatar user-avatar-rounded user-avatar-xl"><img src="chatbox/assets/images/user/80/01.jpg" alt=""></div>
                            <div class="userprofile-name"><span>Calling...</span>
                                <h4>Jack P. Angulo</h4><span>Product Manager</span>
                                <div class="call-duration">00:36</div>
                            </div>
                            <div class="call-options">
                                <div class="row">
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-microphone-off"></i></div>
                                        <h6>Mute</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-volume-high"></i></div>
                                        <h6>Speaker</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-pause"></i></div>
                                        <h6>Hold</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="call-actions">
                                <div class="call-hangup" data-dismiss="modal"><i class="mdi mdi-phone-hangup"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- main wrapper end -->
    <script>
        const camera = document.querySelector('#camera')

        const stop = document.querySelector('#stop')
        const video = document.querySelector('#video')
    </script>
    <script>
        adonis.controller('AdminController', ['sharedData', 'socket', '$scope', '$http', '$window', function(sharedData, socket, $scope, $http, $window) {
            var Admin = this;
            Admin.profile = "chatbox/assets/images/user/150/01.jpg";
            Admin.UserCoverItem = "background-image: url(chatbox/assets/images/media/08.jpg);";
            Admin.UserImages = [];
            const constraints = {
                audio: true,
                video: {
                    width: {
                        min: 1024,
                        ideal: 1280,
                        max: 1920
                    },
                    height: {
                        min: 576,
                        ideal: 720,
                        max: 1080
                    }
                }
            }

            //Camera
            Admin.CameraType = false;
            Admin.CameraStop = function() {
                console.info("Stop Camera");
                if (Admin.cameraStream) {
                    Admin.cameraStream.getTracks().forEach(track => {
                        track.stop()
                    })
                    Admin.cameraStream = null
                }
            }
            Admin.Camera = function() {
                if (!$window.navigator.mediaDevices.getUserMedia(constraints)) console.info("error Camera");
                $window.navigator.mediaDevices.getUserMedia(constraints).then(stream => {
                    Admin.CameraStop();
                    Admin.cameraStream = stream
                    video.srcObject = stream
                    video.play()
                })
            }


            //RecordBlob
            Admin.RecordBlob = function() {

                if (!Admin.cameraStream && !screenStream) return
                const currentStream = Admin.cameraStream || screenStream
                const options = {
                    audioBitsPerSecond: 128000,
                    videoBitsPerSecond: 2500000,
                    mimeType: 'video/webm'
                }
                const mediaRecorder = new MediaRecorder(currentStream, options)
                videoMediaRecorder = mediaRecorder
                mediaRecorder.addEventListener('dataavailable', e => {
                    const blob = new Blob([e.data], {
                        type: 'video/webm'
                    })

                    var formData = new FormData();
                    formData.append('file', blob);
                    var request = $http({
                        method: 'POST',
                        url: 'https://swoole.bestaup.com/Uploads/webm',
                        data: formData,
                        headers: {
                            'Content-Type': undefined
                        },
                    }).then(function successCallback(response) {
                        var data = response.data;
                        console.info(data);
                    }, function errorCallback(response) {
                        // called asynchronously if an error occurs
                        // or server returns response with an error status.

                    });


                    const downloadLink = document.createElement('a')
                    downloadLink.href = window.URL.createObjectURL(blob)
                    downloadLink.download = 'videoName' + Math.floor(Date.now() / 1000);
                    downloadLink.click()
                })
                mediaRecorder.start()

            }

            Admin.RecordStopBlob = function() {
                if (!videoMediaRecorder) return
                videoMediaRecorder.stop()
            }
            //stream
            Admin.StreamPlay = function() {
                const StreamLoad = document.getElementById('StreamLoad');
                const flvPlayer = flvjs.createPlayer({
                    type: 'flv',
                    url: 'https://adonis.tw:8443/live/mark.flv'
                });
                flvPlayer.attachMediaElement(StreamLoad)
                flvPlayer.load();
                flvPlayer.play();
            }
            Admin.StreamLoad = function() {
                if (flvjs.isSupported()) {
                    var request = $http({
                        method: "get",
                        url: "https://adonis.tw/stream.php"
                    }).then(function successCallback(response) {

                    }, function errorCallback(response) {
                        console.info(response);

                    });

                }
            }



            //chatbox
            Admin.Msg = {};
            Admin.getMessage = [];
            socket.onmessage(function(event) {
                var data = JSON.parse(event.data);
                console.info(data);
                Admin.getMessage.push(data);
                $scope.$apply();
            });
            Admin.SendMsg = function() {
                console.info(Admin.Msg);
                socket.send(Admin.Msg);
            }
            if (location.pathname == "/logout") location.href = '';

            Admin.updateMessage = function(message) {
                Admin.Login(message)
            }
            Admin.ReDirect = function(ReDirect) {
                sharedData.ReDirect(ReDirect);
            }
            Admin.Logout = function() {
                sharedData.Logout(ReDirect);
            }
            Admin.UserCover = function(item) {
                Admin.profile = item;
                console.info("Admin.UserCover");
            }
            Admin.Users = function() {
                var Users = {
                    "UniqueID": "",
                }
                var data = {
                    'UniqueID': '',
                    'Action': 'Users',
                    'Data': JSON.stringify(Users),
                }
                var promise = sharedData.List(data);

                promise.then(function(data) { // 呼叫承諾API獲取資料 .resolve  
                    Admin.Users_List = data.List;
                    Admin.UsersPages = data.Pages;
                }, function(data) { // 處理錯誤 .reject  
                    console.info(data);
                });

            };
            Admin.Users();



        }]);
    </script>
    <script>
        (function() {
            $('.btn').click(function() {
                $(this).toggleClass('active');
                return $('.box').toggleClass('open');
            });

        }).call(this);
    </script>
    <!-- Javascripts Files -->
    <script src="chatbox/dist/js/jquery-3.3.1.slim.min.js"></script>
    <script src="chatbox/assets/vendors/bootstrap/bootstrap.bundle.min.js"></script>
    <script src=""></script>
    <script src="chatbox/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="chatbox/assets/vendors/material-floating-button/dist/mfb.min.js"></script>
    <script src="chatbox/dist/js/main.min.js"></script>

</body>

</html>