<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chatriq - Chat & Taskmanager</title>
    <meta name="description" content="The ultimate Bootstrap based Messaging framework to help build Messaging or Chat application fast and easy. Fully responsive and crafted with modern elements and latest design">
    <meta name="keywords" content="Chatriq, chat, messaging, theme, platform" />
    <meta name="subject" content="">
    <meta name="copyright" content="">
    <link rel="icon" href="chatbox/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/materialdesignicons.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/app.min.css">
    <link rel="stylesheet" type="text/css" href="chatbox/dist/css/theme/default-theme.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="login/css/util.css">
    <link rel="stylesheet" type="text/css" href="login/css/main.css">
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css" href="chatbox.css" />

    <!-- Anti-flicker snippet (recommended)  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flv.js/1.3.2/flv.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/4e4a114ffc.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-messages.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/21.2.6/js/dx.all.js"></script>

    <!-- AngularJS Material Javascript now available via Google CDN; version 1.2.1 used here -->
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.2.1/angular-material.min.js"></script>
    <script>
        var adonis = angular.module('Admin', ['ngRoute', 'ngMaterial', 'ngMessages', 'dx']);
        adonis.factory('socket', [function() {
            var stack = [];
            var onmessageDefer;
            var websocket_url = 'wss://swoole.bestaup.com:9509';
            var socket = {
                ws: new WebSocket(websocket_url),
                send: function(data) {
                    data = JSON.stringify(data);
                    if (socket.ws.readyState == 1) {
                        socket.ws.send(data);
                    } else {
                        stack.push(data);
                    }
                },
                onmessage: function(callback) {
                    if (socket.ws.readyState == 1) {
                        socket.ws.onmessage = callback;
                    } else {
                        onmessageDefer = callback;
                    }
                }
            };
            socket.ws.onopen = function(event) {
                for (i in stack) {
                    socket.ws.send(stack[i]);
                }
                stack = [];
                if (onmessageDefer) {
                    socket.ws.onmessage = onmessageDefer;
                    onmessageDefer = null;
                }
            };
            return socket;
        }]);
        adonis.service('sharedData', function($http, $q, $mdToast) {
            var self = this;
            //Toast 
            var last = {
                bottom: true,
                top: false,
                left: false,
                right: true
            };
            self.toastPosition = angular.extend({}, last);

            self.getToastPosition = function() {
                sanitizePosition();

                return Object.keys(self.toastPosition)
                    .filter(function(pos) {
                        return self.toastPosition[pos];
                    }).join(' ');
            };

            function sanitizePosition() {
                var current = self.toastPosition;

                if (current.bottom && last.top) {
                    current.top = false;
                }
                if (current.top && last.bottom) {
                    current.bottom = false;
                }
                if (current.right && last.left) {
                    current.left = false;
                }
                if (current.left && last.right) {
                    current.right = false;
                }

                last = angular.extend({}, current);
            };

            self.Toast = function(Msg, timeout) {
                console.info('Toast', Msg, timeout);
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent(Msg)
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(timeout);

                $mdToast.show(toast)
            }
            self.showActionToast = function() {
                var pinTo = self.getToastPosition();
                var toast = $mdToast.simple()
                    .textContent('Marked as read')
                    .actionKey('z')
                    .actionHint('Press the Control-"z" key combination to ')
                    .action('UNDO')
                    .dismissHint('Activate the Escape key to dismiss this toast.')
                    .highlightAction(true)
                    // Accent is used by default, this just demonstrates the usage.
                    .highlightClass('md-accent')
                    .position(pinTo)
                    .hideDelay(0);

                $mdToast.show(toast)
                    .then(function(response) {
                        if (response === 'ok') {
                            alert('You selected the \'UNDO\' action.');
                        } else {
                            $log.log('Toast dismissed.');
                        }
                    }).catch(function() {
                        $log.log('Toast failed or was forced to close early by another toast.');
                    });
            };
            self.Logout = function() {
                var Data = {}
                Data.UniqueID = "";
                var ReDirect = {
                    'Action': 'Logout',
                    'Data': JSON.stringify(Data),
                }
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/api",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    location.reload();

                }, function errorCallback(response) {

                });
            }
            self.ReDirect = function(ReDirect) {
                var ReDirect = {
                    UniqueID: "",
                    ReDirect: ReDirect
                }
                var ReDirect = {
                    'Action': 'ReDirect',
                    'Data': JSON.stringify(ReDirect),
                }
                console.info(ReDirect);
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/api",
                    data: ReDirect,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    },
                }).then(function successCallback(response) {
                    var data = response.data;
                    if (data.ReDirect == "reload") location.reload();
                    else console.info(data);
                }, function errorCallback(response) {

                });
            }
            //Edit
            self.Edit = function(data) {

                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/ApiEdit",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {

                    if (response.data.Data && response.data.Data.action) {
                        self.Toast('Marked as ' + response.data.Data.action, 3000);
                    } else if (response.data.ErrorMsg) {
                        self.Toast('Marked as ' + response.data.ErrorMsg.join(","), 3000);
                    } else console.info(response.data);
                }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.

                });
            };
            //List
            self.LtstData = {};
            self.List = function(data, key) {
                var deferred = $q.defer();
                var request = $http({
                    method: "post",
                    url: "https://swoole.bestaup.com/UsersApi",
                    data: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8;'
                    }
                }).then(function successCallback(response) {
                    var data = response.data;
                    var Data = {};
                    Data.List = data[data.Action];
                    Data.Pages = data.Pages;
                    deferred.resolve(Data);
                }, function errorCallback(response) {
                    deferred.reject(response);

                });

                return deferred.promise;
            };

        });
    </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css" rel="stylesheet">
    <style>
        .chatapp-user-list {
            flex: 0 0 25%;
        }
    </style>
</head>

<body class="default-theme" ng-app="Admin">
    <!-- Preloader Start -->
    <div class="preloader"></div><!-- Preloader end -->
    <!-- main wrapper start -->
    <div class="main-wrapper" ng-controller="AdminController as Admin">
        <div class="chatapp">
            <!-- navbar start -->
            <nav id="navbar" class="navbar navbar-expand-md navbar-light fixed-top bg-white border-bottom shadow-sm"><a class="navbar-brand" href="index.html"><img src="chatbox/assets/images/logo.svg" width="50" height="50" class="d-inline-block align-top" alt="">
                    <h1>Chatriq</h1>
                </a>
                <div class="ml-auto d-flex align-items-center">
                    <div class="iconbox iconbox-search btn-hovered-light"><i class="iconbox__icon mdi mdi-magnify"></i></div>
                    <div class="navbar-nav">
                        <div class="iconbox-group">
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-wallet-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-diamond-stone"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-bell-ring-outline"></i></div>
                            <div class="iconbox btn-hovered-light"><i class="iconbox__icon mdi mdi-dots-vertical"></i></div>
                        </div>
                        <div class="dropdown user-nav">
                            <div class="user-avatar user-avatar-sm user-avatar-rounded" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="chatriq-user chatriq-user-01"></div>
                            </div>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-outline"></i></span><span>Profile</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-account-multiple-plus-outline"></i></span><span>Invite
                                        People</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-settings-outline"></i></span><span>Settings</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-help-circle-outline"></i></span><span>Help</span></a><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-comment-quote-outline"></i></span><span>Feedback</span></a>
                                <div class="dropdown-divider"></div><a class="dropdown-item" href="javascript:;"><span><i class="mdi mdi-logout-variant"></i></span><span>Logout</span></a>
                            </div>
                        </div>
                        <div class="iconbox-searchbar">
                            <form><input type="text" class="form-control" placeholder="Search here..." autofocus><button class="search-submit" type="submit"><i class="mdi mdi-magnify"></i></button><a href="javascript:void(0)" class="search-close"><i class="mdi mdi-arrow-left"></i></a></form>
                        </div>
                    </div>
                </div>
            </nav><!-- navbar end -->
            <!-- sidebar start -->
            <div class="chatapp__sidebar">
                <ul class="nav" id="myTab" role="tablist">
                    <li class="nav-item"><a class="nav-link active" href="index.html"><i class="mdi mdi-message-text-outline"></i><span>Chats</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="calls.html"><i class="mdi mdi-phone-outline"></i><span>Calls</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="contacts.html"><i class="mdi mdi-account-box-outline"></i><span>Contacts</span></a></li>
                    <li class="nav-item nav-item-todo"><a class="nav-link" href="todo.html"><i class="mdi mdi-checkbox-marked-outline"></i><span>To-Do</span></a></li>
                    <li class="nav-item sidebar-bottom-nav nav-item-help"><a class="nav-link" href="help.html" title="Help"><i class="mdi mdi-help-circle-outline"></i><span>Help</span></a>
                    </li>
                </ul>
            </div><!-- sidebar end -->
            <!-- main content start -->
            <div class="chatapp__content">
                <div class="chatapp__messagetab">
                    <!-- user list start -->
                    <div class="chatapp-user-list">
                        <div class="chatapp-user-list-body custom-scrollbar">
                            <div class="chatapp__headingbar">
                                <h6>All Messages</h6>
                                <div class="chatapp__actions">
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-heart"></i></div>
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-square-edit-outline"></i></div>
                                    <div class="chatapp__actions--icon"><i class="mdi mdi-dots-horizontal-circle-outline"></i>
                                    </div>
                                </div>
                            </div>
                            <ul class="list-unstyled">
                                <li class="" ng-repeat=" item in Admin.Users_List ">
                                    <div class="profile">
                                        <div class="photo"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/764024/profile/profile-512.jpg" />
                                        </div>
                                        <div class="content">
                                            <div class="text">
                                                <h3>{{item.account}}</h3>
                                                <h6>{{item.logined_time}}</h6>
                                            </div>
                                            <div class="action-icon" data-toggle="modal" ng-click="Admin.wsCall(item.UniqueID);" data-target="#UserVideoStart" data-backdrop="static" data-keyboard="false"><i class="mdi mdi-video-outline"></i></div>
                                        </div>

                                        <div class="cards-list">
                                            <div class="card" ng-repeat=" videos in item.videos ">
                                                <div class="card_image"> <img src="" ng-src="video/{{videos}}" />
                                                </div>
                                                <div class="card_title title-white">
                                                    <p>Card Title</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </li>

                            </ul>
                        </div>
                        <ul id="mfbMenu" class="mfb-component--br mfb-slidein-spring" data-mfb-toggle="click">
                            <li class="mfb-component__wrap"><a href="#" class="mfb-component__button--main"><i class="mfb-component__main-icon--resting mdi mdi-plus ion-plus-round"></i><i class="mfb-component__main-icon--active mdi mdi-close ion-close-round"></i></a>
                                <ul class="mfb-component__list">
                                    <li><a href="javascript:;" data-mfb-label="Theme" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-palette"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="Create Group" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-account-group"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="New Call" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-phone"></i></a>
                                    </li>
                                    <li><a href="javascript:;" data-mfb-label="New Chat" class="mfb-component__button--child"><i class="mfb-component__child-icon mdi mdi-android-messages"></i></a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div><!-- user list end -->
                </div>
            </div><!-- main content end -->
        </div><!-- VIDEO CALL START-->
        <div class="modal fade videocall-modal CallDialogFullscreen-sm" id="UserVideoStart" tabindex="-1" role="dialog" aria-labelledby="UserVideoStart" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="icvideocallwrapper">

                            <div class="icvideo-contact">
                                <video id="remoteVideo" autoplay style="width:100%" playsinline></video>
                            </div>
                            <div class="icvideo-user">
                                <video id="localVideo" autoplay style="width:200px;height:100px;" muted="true" playsinline></video>
                            </div>
                            <div class="icvideo-actions">
                                <div class="icvideo-actions__left">
                                    <div class="icvideo-actions__left--duration">00:36</div>
                                </div>
                                <div class="icvideo-actions__middle">
                                    <div class="">
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Speaker"><i class="iconbox__icon mdi mdi-volume-high"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Hold"><i class="iconbox__icon mdi mdi-pause"></i></div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Add Call"><i class="iconbox__icon mdi mdi-phone-plus"></i>
                                        </div>

                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" ng-click="Admin.CameraStop()" data-placement="top" title="Disbale Video">
                                            <i class="iconbox__icon mdi mdi-video-off-outline"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Mute"><i class="iconbox__icon mdi mdi-microphone-off"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="icvideo-actions__right">
                                    <div class="iconbox btn-hovered-light bg-danger" ng-click="Admin.CameraStop();" data-dismiss="modal" data-toggle="tooltip" data-placement="top" title="Hangup"><i class="iconbox__icon text-white mdi mdi-phone-hangup"></i>
                                    </div>
                                </div>
                                <button id="RecordBlob" ng-click="Admin.RecordBlob()">RecordBlob</button>
                                <button id="RecordStopBlob" ng-click="Admin.RecordStopBlob()">RecordStopBlob</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade videocall-modal CallDialogFullscreen-sm" id="incomingVideoStart" tabindex="-1" role="dialog" aria-labelledby="incomingVideoStart" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="icvideocallwrapper">

                            <div class="icvideo-contact"><video id="video" playsinline style="width:100%"></video>
                                <img id="img" style="width:100%">
                                <canvas id="canvas" style="display: none;width:100%"></canvas>
                            </div>
                            <div class="icvideo-user"><img src="chatbox/assets/images/user/150/01.jpg" alt="">
                            </div>
                            <div class="icvideo-actions">
                                <div class="icvideo-actions__left">
                                    <div class="icvideo-actions__left--duration">00:36</div>
                                </div>
                                <div class="icvideo-actions__middle">
                                    <div class="">
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Speaker"><i class="iconbox__icon mdi mdi-volume-high"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Hold"><i class="iconbox__icon mdi mdi-pause"></i></div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Add Call"><i class="iconbox__icon mdi mdi-phone-plus"></i>
                                        </div>

                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" ng-click="Admin.CameraStop()" data-placement="top" title="Disbale Video">
                                            <i class="iconbox__icon mdi mdi-video-off-outline"></i>
                                        </div>
                                        <div class="iconbox btn-hovered-light" data-toggle="tooltip" data-placement="top" title="Mute"><i class="iconbox__icon mdi mdi-microphone-off"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="icvideo-actions__right">
                                    <div class="iconbox btn-hovered-light bg-danger" ng-click="Admin.CameraStop();" data-dismiss="modal" data-toggle="tooltip" data-placement="top" title="Hangup"><i class="iconbox__icon text-white mdi mdi-phone-hangup"></i>
                                    </div>
                                </div>
                                <button id="RecordBlob" ng-click="Admin.RecordBlob()">RecordBlob</button>
                                <button id="RecordStopBlob" ng-click="Admin.RecordStopBlob()">RecordStopBlob</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- OUTGOING VOICE CALL -->
        <div class="modal CallDialogFullscreen-sm" id="outGoingCall" tabindex="-1" role="dialog" aria-labelledby="outGoingCall" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="text-center">
                            <div class="user-avatar user-avatar-rounded user-avatar-xl"><img src="chatbox/assets/images/user/80/01.jpg" alt=""></div>
                            <div class="userprofile-name"><span>Calling...</span>
                                <h4>Jack P. Angulo</h4><span>Product Manager</span>
                                <div class="call-duration">00:36</div>
                            </div>
                            <div class="call-options">
                                <div class="row">
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-microphone-off"></i></div>
                                        <h6>Mute</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-volume-high"></i></div>
                                        <h6>Speaker</h6>
                                    </div>
                                    <div class="col-4">
                                        <div class="call-options__iconbox"><i class="mdi mdi-pause"></i></div>
                                        <h6>Hold</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="call-actions">
                                <div class="call-hangup" data-dismiss="modal"><i class="mdi mdi-phone-hangup"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- main wrapper end -->
    <script type="text/javascript">

    </script>
    <script>
        const camera = document.querySelector('#camera')
        const stop = document.querySelector('#stop')
        const video = document.querySelector('#video')
    </script>
    <script>
        adonis.controller('AdminController', ['sharedData', 'socket', '$scope', '$http', '$window', function(sharedData, socket, $scope, $http, $window) {
            var Admin = this;
            const constraints = {
                audio: true,
                video: {
                    width: {
                        min: 1024,
                        ideal: 1280,
                        max: 1920
                    },
                    height: {
                        min: 576,
                        ideal: 720,
                        max: 1080
                    }
                }
            }

            //Call
            const localVideo = document.getElementById('localVideo');
            const remoteVideo = document.getElementById('remoteVideo');

            navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
            const configuration = {
                iceServers: [{
                    urls: 'stun:stun.l.google.com:19302',
                }, ]
            };
            var pc, localStream;

            function icecandidate(localStream) {
                pc = new RTCPeerConnection(configuration);
                pc.onicecandidate = function(event) {
                    if (event.candidate) {
                        publish('client-candidate', event.candidate);
                    }
                };
                try {
                    pc.addStream(localStream);
                } catch (e) {
                    var tracks = localStream.getTracks();
                    for (var i = 0; i < tracks.length; i++) {
                        pc.addTrack(tracks[i], localStream);
                    }
                }
                pc.onaddstream = function(e) {
                    // $('#remoteVideo').removeClass('hidden');
                    // $('#localVideo').remove();
                    remoteVideo.srcObject = e.stream;
                };
            }

            function publish(event, data) {
                Admin.Call.send(JSON.stringify({
                    cmd: 'publish',
                    subject: Admin.subject,
                    event: event,
                    data: data
                }));
            }

            function subscribe(subject) {
                Admin.Call.send(JSON.stringify({
                    cmd: 'subscribe',
                    subject: Admin.subject
                }));
            }

            function getUrlParam(name) {
                var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
                var r = window.location.search.substr(1).match(reg);
                if (r != null) return unescape(r[2]);
                return null;
            }
            var WS_ADDRESS = 'wss://swoole.bestaup.com:9509';

            Admin.wsCall = function(cid) {
                console.info(cid);
                var answer = 0;

                // 基于订阅，把房间id作为主题
                Admin.subject = 'private-video-room-' + cid;

                // 建立与websocket的连接
                Admin.Call = new WebSocket(WS_ADDRESS);
                console.log(Admin.ws);

                function detectMob() {
                    const toMatch = [
                        /Android/i,
                        /webOS/i,
                        /iPhone/i,
                        /iPad/i,
                        /iPod/i,
                        /BlackBerry/i,
                        /Windows Phone/i
                    ];

                    return toMatch.some((toMatchItem) => {
                        return navigator.userAgent.match(toMatchItem);
                    });
                }
                Admin.Call.onopen = function() {
                    console.log('ws连接');

                    navigator.mediaDevices.getUserMedia({
                        audio: true,
                        video: (detectMob()) ? {
                            width: {
                                min: 1024,
                                ideal: 1280,
                                max: 1920
                            },
                            height: {
                                min: 576,
                                ideal: 720,
                                max: 1080
                            }
                        } : true
                    }).then(function(stream) {
                        localVideo.srcObject = stream;
                        localStream = stream;
                        localVideo.addEventListener('loadedmetadata', function() {
                            publish('client-call', null)
                        });
                    }).catch(function(e) {
                        alert(e);
                    });
                    subscribe(Admin.subject);
                };
                Admin.Call.onmessage = function(e) {
                    var package = JSON.parse(e.data);
                    var data = package.data;
                    switch (package.event) {
                        case 'client-call':
                            console.log('call');

                            icecandidate(localStream);
                            pc.createOffer({
                                offerToReceiveAudio: 1,
                                offerToReceiveVideo: 1
                            }).then(function(desc) {
                                pc.setLocalDescription(desc).then(
                                    function() {
                                        publish('client-offer', pc.localDescription);
                                    }
                                ).catch(function(e) {
                                    alert(e);
                                });
                            }).catch(function(e) {
                                alert(e);
                            });
                            break;
                        case 'client-answer':
                            console.log('answer');

                            pc.setRemoteDescription(new RTCSessionDescription(data), function() {}, function(e) {
                                alert(e);
                            });
                            break;
                        case 'client-offer':
                            console.log('offer');

                            icecandidate(localStream);
                            pc.setRemoteDescription(new RTCSessionDescription(data), function() {
                                if (!answer) {
                                    pc.createAnswer(function(desc) {
                                        pc.setLocalDescription(desc, function() {
                                            publish('client-answer', pc.localDescription);
                                        }, function(e) {
                                            alert(e);
                                        });
                                    }, function(e) {
                                        alert(e);
                                    });
                                    answer = 1;
                                }
                            }, function(e) {
                                alert(e);
                            });
                            break;
                        case 'client-candidate':
                            console.log('candidate');

                            pc.addIceCandidate(new RTCIceCandidate(data), function() {}, function(e) {
                                alert(e);
                            });
                            break;
                    }
                };
            }

            //Camera
            Admin.CameraType = false;
            Admin.CameraStop = function() {
                console.info("Stop Camera");
                if (Admin.cameraStream) {
                    Admin.cameraStream.getTracks().forEach(track => {
                        track.stop()
                    })
                    Admin.cameraStream = null
                }
            }
            Admin.Camera = function() {
                if (!$window.navigator.mediaDevices.getUserMedia(constraints)) console.info("error Camera");
                $window.navigator.mediaDevices.getUserMedia(constraints).then(stream => {
                    Admin.CameraStop();
                    Admin.cameraStream = stream
                    video.srcObject = stream
                    video.play()
                })
            }


            //RecordBlob
            Admin.RecordBlob = function() {

                if (!Admin.cameraStream && !screenStream) return
                const currentStream = Admin.cameraStream || screenStream
                const options = {
                    audioBitsPerSecond: 128000,
                    videoBitsPerSecond: 2500000,
                    mimeType: 'video/webm'
                }
                const mediaRecorder = new MediaRecorder(currentStream, options)
                videoMediaRecorder = mediaRecorder
                mediaRecorder.addEventListener('dataavailable', e => {
                    const blob = new Blob([e.data], {
                        type: 'video/webm'
                    })

                    var formData = new FormData();
                    formData.append('file', blob);
                    var request = $http({
                        method: 'POST',
                        url: 'https://swoole.bestaup.com/Uploads/webm',
                        data: formData,
                        headers: {
                            'Content-Type': undefined
                        },
                    }).then(function successCallback(response) {
                        var data = response.data;
                        console.info(data);
                    }, function errorCallback(response) {
                        // called asynchronously if an error occurs
                        // or server returns response with an error status.

                    });


                    const downloadLink = document.createElement('a')
                    downloadLink.href = window.URL.createObjectURL(blob)
                    downloadLink.download = 'videoName' + Math.floor(Date.now() / 1000);
                    downloadLink.click()
                })
                mediaRecorder.start()

            }

            Admin.RecordStopBlob = function() {
                if (!videoMediaRecorder) return
                videoMediaRecorder.stop()
            }
            //stream
            Admin.StreamPlay = function() {
                const StreamLoad = document.getElementById('StreamLoad');
                const flvPlayer = flvjs.createPlayer({
                    type: 'flv',
                    url: 'https://adonis.tw:8443/live/mark.flv'
                });
                flvPlayer.attachMediaElement(StreamLoad)
                flvPlayer.load();
                flvPlayer.play();
            }
            Admin.StreamLoad = function() {
                if (flvjs.isSupported()) {
                    var request = $http({
                        method: "get",
                        url: "https://adonis.tw/stream.php"
                    }).then(function successCallback(response) {

                    }, function errorCallback(response) {
                        console.info(response);

                    });

                }
            }



            //chatbox
            Admin.Msg = {};
            Admin.getMessage = [];
            socket.onmessage(function(event) {
                var data = JSON.parse(event.data);
                console.info(data);
                Admin.getMessage.push(data);
                $scope.$apply();
            });
            Admin.SendMsg = function() {
                console.info(Admin.Msg);
                socket.send(Admin.Msg);
            }
            if (location.pathname == "/logout") location.href = '';

            Admin.updateMessage = function(message) {
                Admin.Login(message)
            }
            Admin.ReDirect = function(ReDirect) {
                sharedData.ReDirect(ReDirect);
            }
            Admin.Logout = function() {
                sharedData.Logout(ReDirect);
            }
            Admin.Users = function() {
                var Users = {
                    "UniqueID": "",
                }
                var data = {
                    'UniqueID': '',
                    'Action': 'Users',
                    'Data': JSON.stringify(Users),
                }
                var promise = sharedData.List(data);

                promise.then(function(data) { // 呼叫承諾API獲取資料 .resolve  
                    Admin.Users_List = data.List;
                    Admin.UsersPages = data.Pages;
                }, function(data) { // 處理錯誤 .reject  
                    console.info(data);
                });

            };
            Admin.Users();



        }]);
    </script>
    <script>
        (function() {
            $('.btn').click(function() {
                $(this).toggleClass('active');
                return $('.box').toggleClass('open');
            });

        }).call(this);
    </script>
    <!-- Javascripts Files -->
    <script src="chatbox/dist/js/jquery-3.3.1.slim.min.js"></script>
    <script src="chatbox/assets/vendors/bootstrap/bootstrap.bundle.min.js"></script>
    <script src=""></script>
    <script src="chatbox/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="chatbox/assets/vendors/material-floating-button/dist/mfb.min.js"></script>
    <script src="chatbox/dist/js/main.min.js"></script>

</body>

</html>