<!--
=========================================================
* Material Dashboard 2 PRO - v3.0.2
=========================================================

* Product Page:  https://www.creative-tim.com/product/material-dashboard-pro 
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <title>
    註冊信件
  </title>
</head>

<body class="bg-gray-200">
  <!-- Extra details for Live View on GitHub Pages -->
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKDMSK6" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->

  <!-- End Navbar -->
  <main class="main-content  mt-0">
  <p class="mb-4">前往網站輸入認證簡訊碼，已完成本服務註冊。</p>


<div class="text-center">

  <a href="https://swoole.bestaup.com/Auth/SignToken/<?php echo $UniqueID; ?>/<?php echo $Token; ?>" target="_blank">
    <H1>電子郵件 驗證按鈕</H1>
  </a>
</div>
  </main>
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

</body>

</html>